/* eslint-disable */
/* prettier-ignore */

/**
 * Generated by @igniter-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Igniter router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2025-08-21T15:28:33.095Z
 * Framework: generic
 * Output: src/
 */

// Generated by @igniter-js/cli - DO NOT EDIT

export const AppRouterSchema = {
  "controllers": {
    "example": {
      "name": "Example",
      "path": "/example",
      "actions": {
        "health": {
          "path": "/",
          "method": "GET",
          "$Infer": {}
        }
      }
    }
  },
  "docs": {
    "openapi": {
      "openapi": "3.0.0",
      "info": {
        "title": "Igniter API",
        "version": "1.0.0"
      },
      "servers": [
        {
          "url": "http://localhost:3000/api/v1",
          "description": "Default server"
        }
      ],
      "tags": [
        {
          "name": "Example"
        }
      ],
      "paths": {
        "/example": {
          "get": {
            "summary": "health",
            "operationId": "health",
            "tags": [
              "Example"
            ],
            "parameters": [],
            "responses": {
              "200": {
                "description": "Success",
                "content": {
                  "application/json": {
                    "schema": {}
                  }
                }
              }
            }
          }
        }
      },
      "components": {
        "schemas": {},
        "securitySchemes": {}
      }
    },
    "info": {
      "title": "Igniter.js Starter (Bun REST API)",
      "version": "1.0.0",
      "description": "A sample Bun REST API built with Igniter.js"
    }
  }
} as const

export type AppRouterSchemaType = typeof AppRouterSchema
