/**
 * Generated by @flame-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Flame router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2025-07-08T12:24:17.638Z
 * Framework: generic
 * Output: src
 */

import { createFlameClient, useFlameQueryClient } from '@flame-js/core/client'
import type { AppRouterType } from './Flame.router'

/**
  * Type-safe API client generated from your Flame router
  *
  * Usage in Server Components:
  * const users = await api.users.list.query()
  *
  * Usage in Client Components:
  * const { data } = api.users.list.useQuery()
  */
export const api = createFlameClient<AppRouterType>({
  baseURL: Bun.env.BUN_PUBLIC_Flame_API_URL || 'http://localhost:3000',
  basePATH: Bun.env.BUN_PUBLIC_Flame_API_BASE_PATH || '/api/v1',
  router: () => {
    return require('./Flame.schema').AppRouterSchema
  },
})

/**
  * Type-safe API client generated from your Flame router
  *
  * Usage in Server Components:
  * const users = await api.users.list.query()
  *
  * Usage in Client Components:
  * const { data } = api.users.list.useQuery()
  */
export type ApiClient = typeof api

/**
  * Type-safe query client generated from your Flame router
  *
  * Usage in Client Components:
  * const { invalidate } = useQueryClient()
  */
export const useQueryClient = useFlameQueryClient<AppRouterType>;





