/* eslint-disable */
/* prettier-ignore */

/**
 * Generated by @igniter-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Igniter router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2025-08-11T15:16:33.856Z
 * Framework: nextjs
 * Output: src/
 */

// Generated by @igniter-js/cli - DO NOT EDIT

export const AppRouterSchema = {
  "controllers": {
    "message": {
      "name": "Message",
      "description": "Endpoints for Messages",
      "path": "/messages",
      "actions": {
        "list": {
          "name": "list",
          "description": "List all Messages",
          "path": "/",
          "method": "GET",
          "isStream": true
        },
        "getById": {
          "name": "getById",
          "description": "Get a Message by ID",
          "path": "/:id",
          "method": "GET",
          "isStream": false
        },
        "create": {
          "name": "create",
          "description": "Create a new Message",
          "path": "/",
          "method": "POST",
          "isStream": false,
          "bodySchema": {
            "type": "object",
            "properties": {
              "content": {
                "type": "string"
              },
              "sender": {
                "type": "string"
              }
            },
            "required": [
              "content",
              "sender"
            ],
            "additionalProperties": false
          }
        },
        "update": {
          "name": "update",
          "description": "Update a Message by ID",
          "path": "/:id",
          "method": "PUT",
          "isStream": false,
          "bodySchema": {
            "type": "object",
            "properties": {
              "content": {
                "type": "string"
              },
              "sender": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "delete": {
          "name": "delete",
          "description": "Delete a Message by ID",
          "path": "/:id",
          "method": "DELETE",
          "isStream": false
        }
      }
    }
  }
} as const

export type AppRouterSchemaType = typeof AppRouterSchema
