import { ContentSection } from "@/lib/docs";

export const menu: ContentSection[] = [
  {
    title: "Getting Started",
    items: [
      {
        title: "Introduction",
        type: "docs",
        category: "introduction",
        date: new Date().toISOString(),
        description: "Introduction to Flame.js",
        slug: "/docs/",
      },
      {
        title: "Quick Start Guide",
        type: "docs",
        category: "quick-start",
        date: new Date().toISOString(),
        description: "Quick start guide for Flame.js",
        slug: "/docs/getting-started/quick-start-guide",
      },
      {
        title: "Installation",
        type: "docs",
        category: "installation",
        date: new Date().toISOString(),
        description: "How to install Flame.js",
        slug: "/docs/getting-started/installation",
      },
      {
        title: "Project Structure",
        type: "docs",
        category: "project-structure",
        date: new Date().toISOString(),
        description: "Understanding Flame.js project structure",
        slug: "/docs/getting-started/project-structure",
      },
    ],
  },
  {
    title: "Core Concepts",
    items: [
      {
        title: "Core Concepts",
        type: "docs",
        category: "core-concepts",
        date: new Date().toISOString(),
        description: "Core concepts of Flame.js",
        slug: "/docs/core-concepts",
      },
      {
        title: "Flame Builder",
        type: "docs",
        category: "Flame-builder",
        date: new Date().toISOString(),
        description: "Understanding the Flame builder",
        slug: "/docs/core-concepts/Flame-builder",
      },
      {
        title: "Context",
        type: "docs",
        category: "context",
        date: new Date().toISOString(),
        description: "Understanding context in Flame.js",
        slug: "/docs/core-concepts/context",
      },
      {
        title: "Controllers and Actions",
        type: "docs",
        category: "controllers-actions",
        date: new Date().toISOString(),
        description: "Working with controllers and actions",
        slug: "/docs/core-concepts/controllers-and-actions",
      },
      {
        title: "Procedures",
        type: "docs",
        category: "procedures",
        date: new Date().toISOString(),
        description: "Understanding procedures in Flame.js",
        slug: "/docs/core-concepts/procedures",
      },
      {
        title: "Routing",
        type: "docs",
        category: "routing",
        date: new Date().toISOString(),
        description: "Routing in Flame.js",
        slug: "/docs/core-concepts/routing",
      },
      {
        title: "Validation",
        type: "docs",
        category: "validation",
        date: new Date().toISOString(),
        description: "Input validation with Zod",
        slug: "/docs/core-concepts/validation",
      },
    ],
  },
  {
    title: "Client-Side",
    items: [
      {
        title: "Client-Side Integration",
        type: "docs",
        category: "client-side",
        date: new Date().toISOString(),
        description: "Client-side integration with Flame.js",
        slug: "/docs/client-side",
      },
      {
        title: "API Client",
        type: "docs",
        category: "api-client",
        date: new Date().toISOString(),
        description: "Type-safe API client",
        slug: "/docs/client-side/api-client",
      },
      {
        title: "FlameProvider",
        type: "docs",
        category: "Flame-provider",
        date: new Date().toISOString(),
        description: "React context provider setup",
        slug: "/docs/client-side/Flame-provider",
      },
      {
        title: "useQuery",
        type: "docs",
        category: "use-query",
        date: new Date().toISOString(),
        description: "Data fetching with useQuery",
        slug: "/docs/client-side/use-query",
      },
      {
        title: "useMutation",
        type: "docs",
        category: "use-mutation",
        date: new Date().toISOString(),
        description: "Data mutations with useMutation",
        slug: "/docs/client-side/use-mutation",
      },
      {
        title: "useRealtime",
        type: "docs",
        category: "use-realtime",
        date: new Date().toISOString(),
        description: "Real-time subscriptions with useRealtime",
        slug: "/docs/client-side/use-realtime",
      },
    ],
  },
  {
    title: "Advanced Features",
    items: [
      {
        title: "Advanced Features",
        type: "docs",
        category: "advanced-features",
        date: new Date().toISOString(),
        description: "Advanced features of Flame.js",
        slug: "/docs/advanced-features",
      },
      {
        title: "Queues",
        type: "docs",
        category: "queues",
        date: new Date().toISOString(),
        description: "Background job queues with BullMQ",
        slug: "/docs/advanced-features/queues",
      },
      {
        title: "Store",
        type: "docs",
        category: "store",
        date: new Date().toISOString(),
        description: "Redis-based caching and storage",
        slug: "/docs/advanced-features/store",
      },
      {
        title: "Realtime",
        type: "docs",
        category: "realtime",
        date: new Date().toISOString(),
        description: "Real-time features with Server-Sent Events",
        slug: "/docs/advanced-features/realtime",
      },
      {
        title: "OpenAPI Documentation",
        type: "docs",
        category: "openapi-documentation",
        date: new Date().toISOString(),
        description: "Generate OpenAPI specs and HTML docs with the CLI",
        slug: "/docs/advanced-features/openapi-documentation",
      },
      {
        title: "Flame Studio",
        type: "docs",
        category: "Flame-studio",
        date: new Date().toISOString(),
        description: "Flame Studio is a API playground",
        slug: "/docs/advanced-features/Flame-studio",
      }
    ],
  },
  {
    title: "CLI and Tooling",
    items: [
      {
        title: "CLI and Tooling",
        type: "docs",
        category: "cli-tooling",
        date: new Date().toISOString(),
        description: "CLI tools and development utilities",
        slug: "/docs/cli-and-tooling",
      },
      {
        title: "Flame init",
        type: "docs",
        category: "Flame-init",
        date: new Date().toISOString(),
        description: "Initialize new Flame.js projects",
        slug: "/docs/cli-and-tooling/Flame-init",
      },
      {
        title: "Flame dev",
        type: "docs",
        category: "Flame-dev",
        date: new Date().toISOString(),
        description: "Development server and hot reload",
        slug: "/docs/cli-and-tooling/Flame-dev",
      },
      {
        title: "Flame generate",
        type: "docs",
        category: "Flame-generate",
        date: new Date().toISOString(),
        description: "Code generation utilities",
        slug: "/docs/cli-and-tooling/Flame-generate",
      },
      
    ],
  },
  {
    title: "Code Agents",
    items: [
      {
        title: "Introduction",
        type: "docs",
        category: "code-agents-introduction",
        date: new Date().toISOString(),
        description: "Introduction to using AI Code Agents with Flame.js",
        slug: "/docs/code-agents/introduction",
      },
      {
        title: "MCP Server",
        type: "docs",
        category: "mcp-server",
        date: new Date().toISOString(),
        description: "Model Context Protocol server for AI-native development",
        slug: "/docs/code-agents/mcp-server",
      },
      {
        title: "llms.txt",
        type: "docs",
        category: "llms-txt",
        date: new Date().toISOString(),
        description: "Guiding LLMs with a llms.txt file",
        slug: "/docs/code-agents/llms-txt",
      },
      {
        title: "Claude Code",
        type: "docs",
        category: "claude-code",
        date: new Date().toISOString(),
        description: "Using Anthropic's Claude for development",
        slug: "/docs/code-agents/claude-code",
      },
      {
        title: "Cursor",
        type: "docs",
        category: "cursor",
        date: new Date().toISOString(),
        description: "Using Cursor IDE for AI-powered development",
        slug: "/docs/code-agents/cursor",
      },
      {
        title: "Windsurf",
        type: "docs",
        category: "windsurf",
        date: new Date().toISOString(),
        description: "Using Windsurf for AI-powered development",
        slug: "/docs/code-agents/windsurf",
      },
      {
        title: "Zed Editor",
        type: "docs",
        category: "zed-editor",
        date: new Date().toISOString(),
        description: "Using Zed Editor for AI-powered development",
        slug: "/docs/code-gpts/zed-editor",
      },
      {
        title: "Gemini CLI",
        type: "docs",
        category: "gemini-cli",
        date: new Date().toISOString(),
        description: "Using Google's Gemini via CLI",
        slug: "/docs/code-agents/gemini-cli",
      },
      {
        title: "VSCode Copilot",
        type: "docs",
        category: "vscode-copilot",
        date: new Date().toISOString(),
        description: "Using GitHub Copilot in VSCode",
        slug: "/docs/code-agents/vscode-copilot",
      },
    ],
  },
];





