/* eslint-disable @typescript-eslint/no-var-requires */

/**
 * Generated by @flame-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Flame router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2025-08-09T13:02:02.857Z
 * Framework: vite
 * Output: src/
 */

import { createFlameClient, useFlameQueryClient } from '@flame-js/core/client'
import type { AppRouterType } from './Flame.router'

/**
  * Type-safe API client generated from your Flame router
  *
  * Usage in Server Components:
  * const users = await api.users.list.query()
  *
  * Usage in Client Components:
  * const { data } = api.users.list.useQuery()
  */
export const api = createFlameClient<AppRouterType>({
  baseURL: process.env.REACT_APP_Flame_API_URL || 'http://localhost:3000/',
  basePATH: process.env.REACT_APP_Flame_API_BASE_PATH || '/api/v1/',
  router: () => {
    if (typeof window === 'undefined') {
      return require('./Flame.router').AppRouter
    }

    return require('./Flame.schema').AppRouterSchema
  },
})

/**
  * Type-safe API client generated from your Flame router
  *
  * Usage in Server Components:
  * const users = await api.users.list.query()
  *
  * Usage in Client Components:
  * const { data } = api.users.list.useQuery()
  */
export type ApiClient = typeof api

/**
  * Type-safe query client generated from your Flame router
  *
  * Usage in Client Components:
  * const { invalidate } = useQueryClient()
  */
export const useQueryClient = useFlameQueryClient<AppRouterType>;





